#!/bin/bash

num1=$1
num2=$2
num3=$3

if [ $# -ne 3 ]; then
    echo "Error! Enter 3 arguments to the script"
elif [ $num1 -gt $num2 ] && [ $num1 -gt $num3 ]
    echo "$num1 is the greatest"
elif [ $num2 -gt $num3 ]; then
    echo "$num2 is the greatest"
else
    echo "$num3 is the greatest"
fi
